# Generated by Django 5.2 on 2025-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='reeval_fields',
            field=models.JSONField(blank=True, default='["status", "curr_state", "health"]'),
        ),
    ]
