# Generated by Django 5.2 on 2025-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_reeval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='next_upd_ts',
            field=models.BigIntegerField(default=32503679999999),
        ),
        migrations.AlterField(
            model_name='asset',
            name='reeval_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
